### ISSUE TITLE
Adding additonal commands 

### ISSUE THREAD

**Issue by chmpdn** [jupyterlite/terminal#22]
Thanks for creating this amazing and super-useful package.

Currently, it allows only `ls`, `cat`, `pwd` etc. basic commands.
It would be great to have other commands such as `vi` and `ssh`.
Are there any plans to add these in future? If not, could you advise how to add them.

Also, digging into package dependencies, I saw [cockle ](https://github.com/jupyterlite/cockle/blob/c7c1ccdd35e46565ba51e448a7b99db9ff5f2c26/src/commands/coreutils_command_runner.ts#L14) was used which allows more commands which are note directly available in jupyterlite-terminal. Are there any tags/options to enable them?

**Comment by ianthomas23** [comment]
Hello @chmpdn. Thanks for your interest, but this is not ready for anyone else to use yet so you should hold off from using it until we have released a stable version.

Yes, there are plans to add many other commands, and to provide guidance on how end users can write new commands and have them available at runtime.

**Comment by westurner** [comment]
See:
- #23
