### ISSUE TITLE
Terminals not displayed in tree view

### ISSUE THREAD

**Issue by ianthomas23** [jupyterlite/terminal#6]
Opened terminals do not appear in the TERMINALS section of the tree view on the left-hand side of jupyterlite.

**Comment by jtpio** [comment]
We probably need to implement another route that lists the open terminals.

**Comment by jtpio** [comment]
Looks like it's already implemented though: 

https://github.com/jupyterlite/terminal/blob/ccfb5855d0d89149414e9fcf10bedd2d0c1bfbe3/src/terminals.ts#L26-L35
